inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/cucumber.rake'

Metrics/BlockLength:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/FormatStringToken:
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/scheduled_publishing.rake'

Rails/FindBy:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false

Rails/OutputSafety:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Rails/ReversibleMigration:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false
Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: slashes

# This alerts on methods that aren't introduced until rails 6.0
# it should be removed when we upgrade. 
Style/HashEachMethods:
  Enabled: false
