inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/FindBy:
  Enabled: false

# This has special infrastructure for one-time data
# migration tasks, for which it's common to write to
# STDOUT using 'puts'.
Rails/Output:
  Exclude:
    - 'db/data_migration/*.rb'

Rails/HelperInstanceVariable:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false

# This alerts on methods that aren't introduced until rails 6.0
# it should be removed when we upgrade.
Style/HashEachMethods:
  Enabled: false

# We seldom check the return value of 'update' to see if
# the operation was successful. Since we assume success, we
# should raise an exception if this is not the case.
#
# We intend to add this to rubocop-govuk.
Rails/SaveBang:
  Enabled: true
